version: "3"

services:
  database:
    container_name: django_db_service
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:${POSTGRES_PORT}